version: '3.5'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    networks: 
      - default
    ports:
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    environment:
      - "ELASTICSEARCH_USERNAME=yongliang"
      - "ELASTICSEARCH_PASSWORD=Terran1942"
      - "discovery.type=single-node"
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.6.0
    depends_on: 
      - elasticsearch
    networks: 
      - default
    ports: 
      - 5601:5601/tcp
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:6.6.0
    depends_on: 
      - elasticsearch
    networks: 
      - default
    ports: 
      - 5044:5044/tcp
      - 9600:9600/tcp
    volumes: 
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:6.6.0
    depends_on: 
      - logstash
    networks: 
      - default
    volumes: 
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/usr/share/filebeat/logs/
networks: 
  default:
    driver: bridge