version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    networks: 
      - cluster
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.6.0
    depends_on: [elasticsearch]
    networks: 
      - cluster
    ports: 
      - "5601:5601"
    environment:
      # SERVER_NAME: kibana
      # SERVER_HOST: 127.0.0.1
      # SERVER_PORT: 5601
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
networks: 
  cluster:
    driver: bridge