filebeat.prospectors:
  - paths:
      - /usr/share/filebeat/logs/*.log
    multiline:
      pattern: ^\d{4}
      negate: true
      match: after
    fields:
      log_type: game

output.logstash:
  hosts: ["logstash:5043"]