version: '3.5'
services:
  voltdb-1:
    container_name: voltdb-1
    image: voltdb/voltdb-community:8.4
    networks: 
      - cluster
    ports:
      - "11212:21212"
      - "11211:21211"
      - "18080:8080"
    environment:
      HOST_COUNT: 3
      HOSTS:  voltdb-1,voltdb-2,voltdb-3
    volumes:
      - ./data/extend:/opt/voltdb/extend/
      - ./data/snapshot:/opt/voltdb/snapshot/
  voltdb-2:
    container_name: voltdb-2
    image: voltdb/voltdb-community:8.4
    networks: 
      - cluster
    ports:
      - "21212:21212"
      - "21211:21211"
      - "28080:8080"
    environment:
      HOST_COUNT: 3
      HOSTS:  voltdb-1,voltdb-2,voltdb-3
    volumes:
      - ./data/extend:/opt/voltdb/extend/
      - ./data/snapshot:/opt/voltdb/snapshot/
  voltdb-3:
    container_name: voltdb-3
    image: voltdb/voltdb-community:8.4
    networks: 
      - cluster
    ports:
      - "31212:21212"
      - "31211:21211"
      - "38080:8080"
    environment:
      HOST_COUNT: 3
      HOSTS:  voltdb-1,voltdb-2,voltdb-3
    volumes:
      - ./data/extend:/opt/voltdb/extend/
      - ./data/snapshot:/opt/voltdb/snapshot/

networks: 
  cluster:
    driver: bridge