version: '3.5'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    networks: 
      - cluster
    ports:
      - "2181:2181"
  kafka-1:
    container_name: kafka-1
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    networks: 
      - cluster
    ports:
      - "19092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.130
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-2:
    container_name: kafka-2
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    networks: 
      - cluster
    ports:
      - "29092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.130
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-3:
    container_name: kafka-3
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    networks: 
      - cluster
    ports:
      - "39092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.130
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-manager:
    container_name: kafka-manager
    image: sheepkiller/kafka-manager
    depends_on: 
      - zookeeper
      - kafka-1
      - kafka-2
      - kafka-3
    networks: 
      - cluster
    ports: 
      - "19000:9000"
    environment: 
      ZK_HOSTS: zookeeper:2181

networks: 
  cluster:
    driver: bridge